In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

简单的判别方法：左边有几个方括号，就是几维数组

In [4]:
print(arr1.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

1
(2, 3)
6
int64


ndim：返回数组维度

shape:返回元组，表示各个维度元素个数

size：返回数组元素总个数

dtype:数组元素类型（int64：int类型，64比特长度）

In [5]:
arr3 = np.zeros(3)
arr3

array([0., 0., 0.])

创建元素全为零的数组

In [6]:
arr4 = np.ones(3)
arr4

array([1., 1., 1.])

创建全为1的数组（后面有点是因为是浮点型）

In [7]:
np.arange(5, 10, 2)

array([5, 7, 9])

创建数字序列的数组（np.arange（起始值,结束值,步长））结束值不包括在内（前闭后开）

In [8]:
sanwei= np.array([[1,2,3,0],[4,5,6,0],[7,8,9,0]])
sanwei

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [9]:
erwei = np.array([[1,3,7],[4,5,9]])
erwei

array([[1, 3, 7],
       [4, 5, 9]])

In [10]:
arr5 = np.concatenate([arr3, arr4])
arr5

array([0., 0., 0., 1., 1., 1.])

concatenate拼接两个数组（数组类型自动统一）

In [11]:
arr6 = np.array([1, 100, 434, 114514, -243, 355, 43423555, 665, 0, -5123])
print(np.sort(arr6))
print(arr6)

[   -5123     -243        0        1      100      355      434      665
   114514 43423555]
[       1      100      434   114514     -243      355 43423555      665
        0    -5123]


In [12]:
print(arr6.sort())
print(arr6)

None
[   -5123     -243        0        1      100      355      434      665
   114514 43423555]


sort函数排序不改变数组，sort方法改变数组

In [13]:
arr6[1:3]

array([-243,    0])

In [14]:
arr6[6]

np.int64(434)

索引

In [22]:
print(arr1 + arr4)
print(arr1 - arr4)
print(arr1 * arr4)
print(arr2 / erwei)
print(sanwei * 3)
print(arr6.max())
print(arr6.min())
print(arr6.sum())
print(arr6.mean())

[2. 3. 4.]
[0. 1. 2.]
[1. 2. 3.]
[[1.         0.66666667 0.42857143]
 [1.         1.         0.66666667]]
[[ 3  6  9  0]
 [12 15 18  0]
 [21 24 27  0]]
43423555
-5123
43534258
4353425.8


求最大值最小值求和求平均值

In [27]:
arr6[ (arr6>6) &(arr6<114514)]

array([100, 355, 434, 665])

与或非：&|~